module MMCMD
{
    struct MSG
    {
        uint8 msg_type;
        uint8 src_id;
        uint8 dst_id;
        uint8 module_id;
        uint8 func_id;
        uint8 ack1;
        uint8 ack2;
    };
};


